apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    version: 1
    editable: true

  - name: Loki
    type: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    version: 1
    editable: true