{
 "title": "aiqfome API Overview",
 "tags": [
  "api",
  "fastapi",
  "aiqfome"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requisições HTTP por Endpoint (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqs/s" } },
   "targets": [
    {
     "expr": "sum by (endpoint, method, status_code) (rate(http_requests_total[5m]))",
     "legendFormat": "{{method}} {{endpoint}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "Latência Média das Requisições HTTP (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint, method) (rate(http_request_duration_seconds_sum[5m])) / sum by (endpoint, method) (rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "{{method}} {{endpoint}} (Avg Latency)"
    }
   ]
  },
  {
   "title": "Logs da API (Loki)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "forward",
     "expr": "{container_name=\"favoritando-api-1\", service_name=\"api\"} |= ``"
    }
   ]
  }
 ]
}